<?php

return array(
	'SALES_INVOICE_ACCESS' => 1,
	'SALES_INVOICE_CREATE' => 2,
	'SALES_INVOICE_UPDATE' => 3,
	'SALES_INVOICE_DELETE' => 4,
	'SALES_INVOICE_PRINT' => 5,
	'SALES_INVOICE_CONFIRM' => 6,
	'SALES_INVOICE_VOID' => 7,
	'SALES_INVOICE_UNVOID' => 8,

	'PURCHASE_ORDER_ACCESS' => 21,
	'PURCHASE_ORDER_CREATE' => 22,
	'PURCHASE_ORDER_UPDATE' => 23,
	'PURCHASE_ORDER_DELETE' => 24,
	'PURCHASE_ORDER_PRINT' => 25,
	'PURCHASE_ORDER_CONFIRM' => 26,
	'PURCHASE_ORDER_VOID' => 27,
	'PURCHASE_ORDER_UNVOID' => 28,
	'PURCHASE_ORDER_FINISH' => 29,

	'GOODS_IN_ACCESS' => 41,
	'GOODS_IN_CREATE' => 42,
	'GOODS_IN_PRINT' => 43,
	'GOODS_IN_FINIST' => 44,

	'PRODUCT_ACCESS' => 61,
	'PRODUCT_CREATE' => 62,
	'PRODUCT_UPDATE' => 63,
	'PRODUCT_DELETE' => 64,

	'STOCK_TRANSFER_ACCESS' => 81,
	'STOCK_TRANSFER_CREATE' => 82,
	'STOCK_TRANSFER_UPDATE' => 83,
	'STOCK_TRANSFER_DELETE' => 84,
	'STOCK_TRANSFER_PRINT' => 85,
	'STOCK_TRANSFER_CONFIRM' => 86,
	'STOCK_TRANSFER_CONFIRM_DELIVERY' => 87,
	'STOCK_TRANSFER_TRANSFER' => 88,
    'STOCK_TRANSFER_CANCEL' => 89,
	'STOCK_TRANSFER_FINISH' => 90,
	'STOCK_TRANSFER_RETRANSFER' => 92,

	'STOCK_LEVEL_ACCESS' => 101,

	'BRAND_ACCESS' => 121,
	'BRAND_CREATE' => 122,
	'BRAND_UPDATE' => 123,
	'BRAND_DELETE' => 124,

	'SN_TRANSACTION_ACCESS' => 141,

	'QUOTATION_ACCESS' => 161,
	'QUOTATION_CREATE' => 162,
	'QUOTATION_UPDATE' => 163,
	'QUOTATION_DELETE' => 164,
	'QUOTATION_PRINT' => 165,
	'QUOTATION_VOID' => 166,
	'QUOTATION_UNVOID' => 167,

	'REPORT_ACCESS' => 181,

	'DEPOSIT_ACCESS' => 201,
	'DEPOSIT_CREATE' => 202,
	'DEPOSIT_UPDATE' => 203,
	'DEPOSIT_DELETE' => 204,
	'DEPOSIT_PRINT' => 205,
	'DEPOSIT_VOID' => 206,
	'DEPOSIT_UNVOID' => 207,

	'STAFF_ACCESS' => 221,
	'STAFF_CREATE' => 222,
	'STAFF_UPDATE' => 223,
	'STAFF_DELETE' => 224,
	'STAFF_RESET_PASSWORD' => 225,
	'STAFF_ATTENDANCE_ACCESS' => 226,
	'STAFF_ATTENDANCE_CREATE' => 227,

	'STAFF_GROUP_ACCESS' => 241,
	'STAFF_GROUP_CREATE' => 242,
	'STAFF_GROUP_UPDATE' => 243,
	'STAFF_GROUP_DELETE' => 244,

	'CATEGORY_ACCESS' => 261,
	'CATEGORY_CREATE' => 262,
	'CATEGORY_UPDATE' => 263,
	'CATEGORY_DELETE' => 264,
	'CATEGORY_CONFIRM' => 265,

	'SUPPLIER_ACCESS' => 281,
	'SUPPLIER_CREATE' => 282,
	'SUPPLIER_UPDATE' => 283,
	'SUPPLIER_DELETE' => 284,

	'STOCK_TRANSPORT_LOG_ACCESS' => 301,
);
